version: "3.9"

name: NetSite

services:
  netsite:
    image: jvilaplana/netsite
    container_name: app
    build:
      context: NetSite
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - MongoDb__ConnectionString=mongodb://mongo:mongo@mongo:27017
      - MongoDb__DatabaseName=netsite
    networks:
      - netsite-network

  # MongoDB service
  mongo:
    image: mongo:8.0
    container_name: db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - netsite-data:/data/db
    networks:
      - netsite-network

volumes:
  netsite-data:

networks:
  netsite-network:

